export zubat from './flying_zubat.gif';
export masterball from './master_ball.png';
export masterballCave from './masterball_cave.jpg';
export mewtwoCave from './mewtwo_cave.jpg';
export mewtwo from './mewtwo.png';
export pokemonCenter from './pokecenter.jpg';
export pokeDollCave from './pokedoll_cave.jpg';
export pokeDoll from './pokedoll.png';
export startCave from './start_cave.jpg';